name: Scrape & skeet

permissions:
  contents: write

on:
  push:
  workflow_dispatch:
  schedule:
    # Run at ~7:04am PST every day
    - cron:  '4 3 * * *'
    # Run at ~7:04pm PST every day
    - cron:  '4 15 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.19.0

      - name: Check out this repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install

      # Note that this will also check if there are changes AND skeet them to Bsky
      - name: Build and run
        run: yarn start
        env:
          BLUESKY_USERNAME: ${{ env.BLUESKY_USERNAME }}
          BLUESKY_PASSWORD: ${{ env.BLUESKY_PASSWORD }}

      # At this point, we may have already done the skeeting part, this just ensures that we update the local data
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "📱 Latest data: ${timestamp}" || exit 0
          git pull --rebase origin main
          git push
