name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    # Note that we intentionally do this slightly off the hour,
    # as other scrapers are more likely to use the exact hour.
    - cron:  '6 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.19.0

      - name: Check out this repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install

      - name: Build and run
        run: yarn start

      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
